# 언어 설정
lang: en

# 메인 화면 및 페이지 상단 제목
title: yu bin, kim
sub_title: Yonsei Univ (ME/CS)

# web의 주소 설정
url: "https://ybkim95.github.io"
baseurl: "" 

# 설명
description: >- # this means to ignore newlines until "baseurl:"
  Robotics Engineer

# 사이트 메인 화면 이미지 및 로고
accent_image: "/assets/img/ybk_teaser.jpg"
logo: "/assets/icons/ybk_logo.jpg"

# 저자 정보
author:
  name: 'Yu Bin, Kim'
  email: ybkim95@yonsei.ac.kr
  facebook_username: kimyoubin25
  github_username: ybkim95
  linkedin_username: ybkim95

# Build settings
plugins:
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
